version: '3.8'
services:
  
  frontend:
    image: wecanwalk/songspot-client:latest
    container_name: react_app
    ports:
      - "3000:3000"

  controller:
    image: wecanwalk/songspot-server:latest
    container_name: springboot_app
    ports:
      - "8080:8080"
    environment:
      spring_profiles_active: dev
    volumes:
      - $HOME/docker/volumes/log:/d/var/log

  cache:
    image: redis
    container_name: cache
    ports:
      - "127.0.0.1:6379:6379"

  database:
    image: postgres
    container_name: db
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: postgres
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    restart: unless-stopped
