version: '2.1'
services:
  
  frontend:
    image: wecanwalk/songspot-frontend:latest
    container_name: react_app
    ports:
      - "3000:3000"
    depends_on:
      - controller

  controller:
    image: wecanwalk/songspot-backend:latest
    container_name: springboot_app
    ports:
      - "8080:8080"
    environment:
      spring_profiles_active: dev
    volumes:
      - $HOME/docker/volumes/log:/d/var/log
    depends_on:
      database:
        condition: service_healthy

  cache:
    image: redis
    container_name: cache
    ports:
      - "127.0.0.1:6379:6379"

  database:
    image: postgres
    container_name: db
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: postgres
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
