version: '3.8'
services:

  frontend:
    image: wecanwalk/songspot-client:1.0.0
    container_name: react_app
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - controller

  controller:
    image: wecanwalk/songspot-server:1.0.0
    container_name: springboot_app
    ports:
      - "8080:8080"
    environment:
      spring_profiles_active: prod
    volumes:
      - $HOME/docker/volumes/log:/var/log

  cache:
    image: redis
    container_name: cache
    ports:
      - "127.0.0.1:6379:6379"

  database:
    image: postgres
    container_name: db
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: postgres
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    restart: unless-stopped